# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 60392bcf53d3a8dcbc858962782326b89a1cf8251d84e351203c48b50a429c3a949b46b297a5439d257031ba9e12b8cb2805425c4f7e9664971b220f70e24d93

test:
  secret_key_base: 751a896c4a36196b3c34589a28685f6eb8374a6b0ecda4226c87e03a40fb80bd63e8ddd05872bf6eb08d37257869241eeeaffa1fd5f1e33904d6bacd52a3c0fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
